AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Set Roles and Policies for {{ cookiecutter.project_slug }} stack.

Metadata:
  Author: Jake Hickenlooper

Parameters:
  ProjectSlug:
    Type: "String"
    Description: Should not change. See build-change-set.cfn.yaml
    Default: "{{ cookiecutter.project_slug }}"
    AllowedValues:
      - "{{ cookiecutter.project_slug }}"

Resources:

  UpdateStaticWebsiteServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Description: >
        For CodeBuild and Lambda projects that need to update objects in static
        website and artifact S3 buckets.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  UpdateStaticWebsitePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "UpdateStaticWebsitePolicy"
      Roles:
        - !Ref "UpdateStaticWebsiteServiceRole"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:DeleteObject"
              - "s3:ListObjectsV2"
            Resource:
              - !Sub
                - "${staticwebsitebucketarn}/${ProjectSlug}/*"
                -
                  staticwebsitebucketarn:
                    Fn::ImportValue: "root-StaticWebsiteBucketArn"
          -
            Effect: Allow
            Action:
              - "s3:ListBucket"
              - "s3:GetBucketLocation"
            Resource:
              -
                Fn::ImportValue: "root-StaticWebsiteBucketArn"
              -
                Fn::ImportValue: "root-ArtifactBucketArn"
          -
            Effect: Allow
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:ListObjectsV2"
            Resource:
              - !Sub
                - "${artifactbucketbucketarn}/staticbuild/${ProjectSlug}/*"
                -
                  artifactbucketbucketarn:
                    Fn::ImportValue: "root-ArtifactBucketArn"
          -
            Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              - !Sub
                - "${pipelinebucketarn}/*"
                -
                  pipelinebucketarn:
                    Fn::ImportValue: "root-PipelineBucketArn"
          -
            Action:
              - "codepipeline:PutJobSuccessResult"
              - "codepipeline:PutJobFailureResult"
            Effect: "Allow"
            Resource: "*"
          -
            Effect: Allow
            Action:
              - "logs:CreateLogStream"
              - "logs:CreateLogGroup"
              - "logs:PutLogEvents"
            Resource:
              - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:${ProjectSlug}-*:log-stream:*"
              - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:${ProjectSlug}-*"

Outputs:

  UpdateStaticWebsiteServiceRole:
    Value: !Ref UpdateStaticWebsiteServiceRole
    Export:
      Name: !Sub "${ProjectSlug}-UpdateStaticWebsiteServiceRole"
  UpdateStaticWebsiteServiceRoleArn:
    Value: !GetAtt UpdateStaticWebsiteServiceRole.Arn
    Export:
      Name: !Sub "${ProjectSlug}-UpdateStaticWebsiteServiceRoleArn"
